% This script is to add necessary line segments in Gap to RCU bound vs.
% Complexity plot originally generated by Ethan.
%
% Written by Hengjie Yang (hengjie.yang@ucla.edu)   03/10/21.
%

clear all;
clc;

path = './TCOM_sim_data/';
fileName = 'RCU_Complexity_10_3';
fig = openfig([path, fileName, '.fig']);


%%
Xs = cell(6, 1);
Ys = cell(6, 1);

% m + v = 6
Xs{1} = [2847.3232, 11661];
Ys{1} = [1.5814, 1.5478];

% m + v = 8
Xs{2} = [3000.7469, 4459.5302, 7382.795, 44499];
Ys{2} = [1.2205, 1.2505, 1.1913, 1.0973];

% m + v = 10
Xs{3} = [3279.5791, 4692.5543, 7664.3998, 13528.6949, 24950.8883, 171225];
Ys{3} = [0.973, 0.95707, 0.9239, 0.89675, 0.92879, 0.81966];

% m + v = 13
Xs{4} = [4616.9016, 5550.6535, 8336.8057, 14332.4643, 26245.6894, 49478.1381, 94492.7334, 189503.2105, 1294562];
Ys{4} = [0.71499, 0.64365, 0.63616, 0.59533, 0.58237, 0.56353, 0.58965, 0.59896, 0.58145];

% m + v = 15
Xs{5} = [9520.8036, 15205.5738, 27300.9289, 51174.6999, 97668.3465, 187720.0054];
Ys{5} = [0.53157, 0.48851, 0.48505, 0.45851, 0.46165, 0.45428];

% m + v = 17
Xs{6} = [28959.9091, 53207.3697, 101021.5667, 194011.7902];
Ys{6} = [0.35391, 0.36885, 0.34897, 0.37532];


%% plot line segments

plot(Xs{1}, Ys{1}, '--k', 'HandleVisibility','off'); hold on
plot(Xs{2}, Ys{2}, '--k', 'HandleVisibility','off'); hold on
plot(Xs{3}, Ys{3}, '--k', 'HandleVisibility','off'); hold on
plot(Xs{4}, Ys{4}, '--k', 'HandleVisibility','off'); hold on
plot(Xs{5}, Ys{5}, '--k', 'HandleVisibility','off'); hold on
plot(Xs{6}, Ys{6}, '--k', 'HandleVisibility','off'); hold on

% x = [1.1*1/3, 1*1/3];
% y = [1.05*0.583, 1.05*0.533];
% annotation('textarrow', x, y, 'String', '$m+\nu = 6$', 'interpreter','latex');

x = [0.36, 0.32];
y = [1*0.6, 1*0.55];
annotation('textarrow', x, y, 'String', '$m+\nu = 6$', 'interpreter','latex');

x = [0.44, 0.4];
y = [0.49, 0.44];
annotation('textarrow', x, y, 'String', '$m+\nu = 8$', 'interpreter','latex');

x = [0.6, 0.9*0.62];
y = [1*0.42, 1*0.37];
annotation('textarrow', x, y, 'String', '$m+\nu = 10$', 'interpreter','latex');

x = [0.3, 0.35];
y = [0.23, 0.27];
annotation('textarrow', x, y, 'String', '$m+\nu = 13$', 'interpreter','latex');

x = [0.36, 0.4];
y = [0.18, 0.24];
annotation('textarrow', x, y, 'String', '$m+\nu = 15$', 'interpreter','latex');

x = [0.56, 0.59];
y = [0.16, 0.2];
annotation('textarrow', x, y, 'String', '$m+\nu = 17$', 'interpreter','latex');
